name: shakespeare-sass
version: "0.1.4.1"
synopsis: SASS support for Shakespeare and Yesod
description: SASS support for Shakespeare and Yesod
category: Web
author: Filip Brcic
maintainer: brcha@yandex.com
license: BSD3
github: brcha/shakespeare-sass
extra-source-files:
  - README.md
default-extensions:
  - TemplateHaskell
  - QuasiQuotes
dependencies:
  - base >= 4 && < 5
  - template-haskell
  - yesod
  - yesod-core
  - shakespeare
  - hsass
library:
  source-dirs: src
  exposed-modules:
    - Text.Shakespeare.Sass
